#### Promise多种错误检测和catch

promise函数中有隐式的try catch 遇到异常时会自动捕获

用catch可以捕获流程中catch前中可能存在的promise的异常

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
<script>
    new Promise((resolve, reject) => {
        reject(new Error("promise fail"))
        // throw new Error("promise fail")
        // hd + 1;
    }).then(value => {
        console.log(value)
    }).catch(err => {
        console.log(err)
    })
</script>
</html>
```

